"""add pre_score to candidates

Revision ID: d8c0b5bc59fa
Revises: b7263d6c3699
Create Date: 2026-07-02 12:15:42.723954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c0b5bc59fa'
down_revision = 'b7263d6c3699'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('pre_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'pre_score')
    # ### end Alembic commands ###
